apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-noticias
spec:
  replicas: 2
  selector:
    matchLabels:
      app: portal-noticias
  template:
    metadata:
      labels:
        app: portal-noticias
    spec:
      containers:
        - name: portal-noticias
          image: aluracursos/portal-noticias:1
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              cpu: "50m"
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: portal-configmap
          livenessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 10
            failureThreshold: 3
            initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 10
            failureThreshold: 3
            initialDelaySeconds: 30
