apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-noticias
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-noticias
  template:
    metadata:
      labels:
        app: api-noticias
    spec:
      containers:
        - name: api-noticias
          image: aluracursos/sistema-noticias:1
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              cpu: "50m"
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: api-configmap
          livenessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 10
            failureThreshold: 3
            initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 10
            failureThreshold: 3
            initialDelaySeconds: 30
