apiVersion: v1
kind: Pod
metadata:
  name: api-noticias
  labels:
    app: api-noticias
spec:
  containers:
    - name: api-noticias
      image: aluracursos/sistema-noticias:1
      ports:
        - containerPort: 80
      envFrom:
        - configMapRef:
            name: api-configmap
        
